### ISSUE TITLE
RDNAPTRANS™ 2008/2018

### ISSUE THREAD

**Issue by pjo64** [Geonovum/HR-CRS-Gebruik#12]
De handreiking vermeldt nergens het gebruik van RDNAPTRANS™2008, terwijl het einde van de overgangsperiode van 2008 naar 2018 nog niet is vastgelegd (volgens de NSGI). Daaruit begrijp ik dat momenteel zowel RDNAPTRANS™2008 als RDNAPTRANS™2018 gebruikt mogen worden. Het advies van de NSGI aan gebruikers met hoge eisen aan de nauwkeurigheid van de hoogte is zelfs om vooralsnog gebruik te blijven maken van RDNAPTRANS™2008. Het lijkt me goed om in de handreiking hier ook wat woorden aan te besteden.

Aangezien er op dit moment dus twee geldige transformaties naar tussen ETRS89 en RD/NAP bestaan, achten de auteurs het van belang om in een bestand aan te geven welke van de twee gebruikt is? En zo ja, hoe? Voor zover ik kon vinden zijn er geen nieuwe EPSG codes, naast de bestaande codes 28992 (2D), 5709 (1D) en 7415 (Compound), Op zich is dat ook logisch, het systeem zelf is niet veranderd, alleen de transformatie ETRS89 en RD/NAP.

**Comment by lhuisman** [comment]
Peter, allereerst hartelijk dank voor de feedback.

In de handreiking wordt het vastleggen van de gebruikte transformatie geadviseerd in:
* paragraaf 3.1.1 (4e bullet)
* 3.2 (2e bullet)
* 3.2.2.2.2 (aanbeveling)

Er is geen advies beschikbaar waar de in handreiking naar verwezen kan worden over hoe dit eenduidig te doen. Er is wel een voorbeeld opgenomen van de BRO (paragraaf 3.2.2.2.2 laatste voorbeeld)

Met betrekking tot het advies van de NSGI voor gebruik van RDNAPTRANS versies pas ik de verwijzing naar de website van NSGI aan in paragraaf 3.2.2.1 aan.

Ter informatie: Naast EPSG-codes voor CRS-en bestaan er ook EPSG-codes voor transformaties (maar helaas niet voor alle RDNAPTRANS varianten).

Voor RDNAPTRANS2018 is bijvoorbeeld:
* de transformatiecode voor ETRS89-GRS80h naar ETRS89-GRS80 + NAP volgens 'variant 1': [9597](https://epsg.org/transformation_9597/ETRS89-to-ETRS89-NAP-height-2.html)
* de transformatiecodes voor ETRS89-GRS80 naar RD volgens 'variant 2': [9281](https://epsg.org/transformation_9282/Amersfoort-to-ETRS89-9.html)
