### ISSUE TITLE
paragraaf 2.4.2 missende definitie begrip "coördinatenstelsel"

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/HR-CRS-Gebruik#13]
Ik mis de definitie van het begrip "coördinatenstelsel" terwijl dat wel in deze paragraaf voor het eerst wordt gebruikt.
Is dat hetzelfde als een CRS, of toch iets anders?

Hierdoor is niet helemaal duidelijk wat bedoeld wordt met de zin: "Het Europese ETRS89 (European Terrestrial Reference System 1989) is daarmee sinds 1 oktober 2000 het officiële driedimensionale **coördinatenstelsel** van Nederland."

**Comment by lhuisman** [comment]
Hier wordt inderdaad CRS bedoeld. Hetzelfde geldt voor de zin de daarna waar in plaats van coördinatensysteem CRS wordt bedoeld. Aangepast in tekst.

Daarnaast wordt in het voorbeeld van paragraaf 2.4.2.2 ook CRS bedoeld i.p.v. coördinatenstelsel, maar hier is het een citaat. Daarom opmerking toegevoegd.
