### ISSUE TITLE
paragraaf 2.4.2.1 Realisaties van ETRS89

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/HR-CRS-Gebruik#14]
Wat wordt nu precies bedoeld met "realisatie"?

**Comment by lhuisman** [comment]
Introductie van realisatie teogevoegd aan het eidne van paragraaf 2.1:

*Om coördinaten te kunnen bepalen volgens de definitie van een CRS wordt een CRS fysiek gerealiseerd. Het NAP wordt gerealiseerd door hoogten van punten (peilmerken) te bepalen volgens de definitie van NAP op basis van (waterpas)metingen. De NAP-peilmerken dienen als referentiepunten voor gebruik van de NAP-realisatie. Tussen verschillende realisaties van een CRS bestaan verschillen door gebruik van andere metingen, rekentechnieken en punten. De eerste realisatie van WGS 84 in 1987 werd bijvoorbeeld berekend met behulp van Doppler waarnemingen met het TRANSIT satellietsysteem, terwijl de realisatie van 2021 is bepaald op basis van GPS-waarnemingen. De verschillen tussen deze WGS 84 realisaties is meer dan 1 meter.*
