### ISSUE TITLE
Gebruik van meerdere CRS-en in OGC-API-Features

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/HR-CRS-Gebruik#15]
Het lijkt mij goed om ergens in hoofdstuk 3 aandacht te besteden aan hoe OGC-API's omgaan met meerdere CRS-en.
Voor OGC-API Features is recent een standaard daarvoor vastgesteld: https://docs.opengeospatial.org/is/18-058/18-058.html

**Comment by lhuisman** [comment]
Paragraaf over OGC API toegevoegd

https://github.com/Geonovum/HR-CRS-Gebruik/commit/29557dd80c085626361b7b434842054ab6ffc13c
