### ISSUE TITLE
Verkeerde EPSG code

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/HR-CRS-Gebruik#18]
In het CRS overzicht in [Bijlage A](https://geonovum.github.io/HR-CRS-Gebruik/#bijlage-a-crs-overzicht-tabel) staat een foutje.  Bij WGS 84 staat de EPSG code van ETRS 89, `4258`.

**Comment by frisopenninga** [comment]
Klopt, goede code is 4326. Aanpassing doorgevoerd  op 25/4
